[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["cd Server && npm ci"]

[phases.build]
cmds = ["echo 'Build completed from Server directory'"]

[start]
cmd = "cd Server && node app.js"

